### ISSUE TITLE
how can i run this code. i need to your help

### ISSUE THREAD

**Issue by thebadthebadthebad** [biointec/jesse#18]
Hi, I am KyeongRok, graduated student in korean, sungkyunkwan university.

I am interested in graphlet and graph neural network.
so I found your graphlet searching code and It is good that I have found.
But i was in trouble running the code.

I installed mavon and compile your code into .jar format.

And I run the jar file using 'java -jar jesse-1.1.0.jar.
I made the my graph .txt file containing simple graph(A  B, B  C) and answer my graph file name to "Enter file name for the graph:"
but result file is 
0 1,
0 2,1 2,
2 0,1 0,
0 1,0 2,1 2,.
And it is not right result because format is different from suggesting result(
nodename number of 0 orbit, number of 1 orbit.... 
othenodename other orbit..
can you help me run this code?

i am curious about that where should i save the graph file(txt)(i saved graph file to place same with jesse-1.1.0.jar file after compiling) and what exact graph file format is.

Thank you for leading my question
[graph1.txt](https://github.com/biointec/jesse/files/7931325/graph1.txt)
[result.txt](https://github.com/biointec/jesse/files/7931328/result.txt)
.

**Comment by thebadthebadthebad** [comment]
graph file and result file is attached.

**Comment by thebadthebadthebad** [comment]
I was run your code but file contained orbit having minus(-1) and tremendous numbers(2343242)

Is the code not working very accurately?
Is it my fault or Is it a matter of realization
[4.txt](https://github.com/biointec/jesse/files/7931879/4.txt)
?

**Comment by Simonvde** [comment]
Dear KeongRock,

I tested the algorithm for your graph and find the correct output. See: [result.txt](https://github.com/biointec/jesse/files/7932111/result.txt).

Here I include an instruction set for the terminal that should give you a working example: [Jesse_example.md](https://github.com/biointec/jesse/files/7932129/Jesse_example.md)

If this doesn't work, please detail your file locations and terminal input exactly so that I can help you further.

**Comment by thebadthebadthebad** [comment]
Thank you for answering.
I also checked your code work very well too!
But i don't understand why some orbit number is minus or too big.
I attached my graph and result. 

I want to find orbit of five node graphlet.

my graph is BA-shapes graph of torch_geometric having 700 nodes and 3944 edges.

thank you for your attention.

[result.txt](https://github.com/biointec/jesse/files/7932946/result.txt)

[bashpes.txt](https://github.com/biointec/jesse/files/7932945/bashpes.txt)

**Comment by Simonvde** [comment]
The graph you provide is directed. This version of the application only works for simple undirected graphs. If you are interested in more complicated types of graphlets (i.e. non-simple), you can look at chapter 5 of this thesis: Melckenbeeck, Ine. _Extension of graphlets to larger order and generic graph types._ Diss. Ghent University, 2019.

**Comment by thebadthebadthebad** [comment]
Thank you for answering.

The BAshapes graph is undirected graph(attached at upper) 
It is not directed graph and i also want to use it as a undirected graph.
And I think that it is not important because this jesse code can accept simple graph data(just node-node, not directed or undirected) so i still am not understand the result(minus and too large scale number)

i am curious about what a code works well at a other graphs.  Is my situation special case?.

In addition, I am so grateful for your sincere answers.

**Comment by Simonvde** [comment]
It is important to the Jesse implementation. Your graph file contains every edge twice (e.g. 695 48 and 48 695). I tested the code with an adapted graph file (removing every double edge) and the results seem as expected. Here is your graph without double edges:
[bashpes_undirected.txt](https://github.com/biointec/jesse/files/7940196/bashpes_undirected.txt)

**Comment by thebadthebadthebad** [comment]
Ok.

I  confirmed that the code runs well.
I'm truly grateful for your kindness.

I will always remember the kindness you showed me. 
I hope to see you someday through good research.

Once again, Thank you very much
